# Generated by Django 4.2.7 on 2023-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=45)),
                ('last', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.TextField()),
            ],
        ),
    ]
